### ISSUE TITLE
interp_light masking

### ISSUE THREAD

**Issue by marosteg** [camrinbraun/tags2etuff#33]
Certain datasets run through interp_light with mask=TRUE work just fine while others fail with:

Error in `[<-`(`*tmp*`, c((maxZ[i, 2] + 1):nrow(results$sm_data)), i,  : 
  subscript out of bounds

Unclear what the mismatch given that superficially nothing is particularly different about one dataset or another (and it's not a Wildlife vs Lotek issue).

**Comment by camrinbraun** [comment]
example of a tag ID that fails?

**Comment by camrinbraun** [comment]
B2398

**Comment by camrinbraun** [comment]
can you send the bit of your code that includes the hack for fixing the etuff metadata issue in `read_archival`? I assume the workflow is just:
```
## some hacky fix for obsTypes
#????

etuff_file <- '~/Google Drive/My Drive/Albacore - All Data/data/172419_2004_B2398/cdb/172419_2004_B2398_eTUFF.txt'
etuff <- read_archival(etuff_file)

series <- get_series(etuff)
## filter for daytime only
series$dn <- add_daynight(series, etuff)
series_dayOnly <- series %>% filter(dn == 'd' & !is.na(depth) & !is.na(light))

## do the interp
results <- interp_light(series_dayOnly, mask = TRUE)
#^^^ error is here

```

**Comment by marosteg** [comment]
[metaTypes.csv](https://github.com/camrinbraun/tags2etuff/files/10889357/metaTypes.csv)

metaTypes <- read.csv("metaTypes.csv",header=T)

dir <- '~/Google Drive/Shared drives/MPG_WHOI/data/albacore/'

albacore <- list.files(dir)
albacore <- albacore[albacore %like% "172419"] # generate list of unique fishIDs

z = 14 #B2398
fishID <- albacore[z] # specify the individual
  
data_dir <- paste(dir, fishID, '/cdb/', sep='')

etuff <- read_archival(paste(data_dir,fishID,"_eTUFF.txt",sep=""),metaTypes = metaTypes)

ts <- get_series(etuff) ## I hacked this to provide you the light data that’s in the stuff already
ts[which(ts$depth<0),"depth"] <- 0 # assigns entries with negative depth (above surface) readings as depth zero (at surface)

ts$dn <- add_daynight(ts, etuff)
ts_dayOnly <- ts %>% filter(dn == 'd' & !is.na(depth) & !is.na(light))
results <- interp_light(ts_dayOnly, mask = TRUE)

ts_dayOnly$day_vec <- as.integer(as.Date(ts_dayOnly$DateTime)) - min(as.integer(as.Date(ts_dayOnly$DateTime))) + 1
day_vec <- results$xgrid
depth_vec <- results$ygrid
image(day_vec, depth_vec, t(results$sm_data), axes=T, ylim=c(max(depth_vec),0))

**Comment by camrinbraun** [comment]
@marosteg https://github.com/camrinbraun/tags2etuff/pull/34 should fix it

**Comment by marosteg** [comment]
Works now, thanks!
