### ISSUE TITLE
get_tad() mismatch

### ISSUE THREAD

**Issue by marosteg** [camrinbraun/tags2etuff#37]
I've come across an issue with **get_tad()** in which two different problems can arise depending on the tag (presumably due to formatting changes across model years of miniPATs). For example, I'm looking at shortbill spearfish miniPATs all with the same TAD bin programming (11 bins, final bin with max depth of 300 m). For spearfish ptt-202432, the call to **get_tad()** yields only 9 bins, with the final bin of max depth 200 m (missing 200-250 and 250-300). All other spearfish ptts (e.g., ppt-227130) instead yield 12 bins, with bin 12 actually being a repeat of bin 1 as far as bin min (0 m) and max (5 m) are concerned (but yielding a different 'freq' value).

Interestingly, this issue is not present in get_tat().

MWE:
```
devtools::load_all('~/Dropbox/GitHub/tags2etuff')
devtools::load_all('~/Dropbox/GitHub/HMMoce')

#Read in metadata
meta <- read.csv('add_shortbillspearfish_meta.csv',header=T)
## format dates
meta$time_coverage_start <- lubridate::parse_date_time(meta$time_coverage_start, orders='Ymd HMS', tz='UTC')
meta$time_coverage_end <- lubridate::parse_date_time(meta$time_coverage_end, orders='Ymd HMS', tz='UTC')

dir <- '~/Google Drive/Shared drives/MPG_WHOI/data/shortbill_spearfish/MiniPAT/'

fish <- list.files(dir)
fish <- fish[-c(8,9)]

i = 1 # ptt 20243
fishID <- fish[i] # specify the individual
  etuffID <- meta[which(meta$ptt==fishID),"instrument_name"] # specify the individual (etuff format)
  data_dir <- paste(dir, fishID, sep='')
  etuff <- tag_to_etuff(dir=data_dir, meta=meta[which(meta$ptt == fishID),], gpe3 = FALSE)
  tad_missingbin <- get_tad(etuff)

i = 2 # ptt 227130
fishID <- fish[i] # specify the individual
  etuffID <- meta[which(meta$ptt==fishID),"instrument_name"] # specify the individual (etuff format)
  data_dir <- paste(dir, fishID, sep='')
  etuff <- tag_to_etuff(dir=data_dir, meta=meta[which(meta$ptt == fishID),], gpe3 = FALSE)
  tad_extrabin <- get_tad(etuff)
```

[add_shortbillspearfish_meta.csv](https://github.com/camrinbraun/tags2etuff/files/11994342/add_shortbillspearfish_meta.csv)

**Comment by camrinbraun** [comment]
All modern miniPATs have 12 bins for both TAD and TAT.

> For spearfish ptt-202432, the call to **get_tad()** yields only 9 bins, with the final bin of max depth 200 m (missing 200-250 and 250-300). 

This is because bins after the 9th bin with max of 200m have no data. The current behavior is to remove NAs which results in no data in bins 10 (200-250), 11 (250-300) and 12 (300-2000). Is the desired behavior to retain those bins with freq=0?

**Comment by marosteg** [comment]
Yes, we should retain the bins with freq=0 and have the value listed as 0 rather than NA.

**Comment by camrinbraun** [comment]
> All other spearfish ptts (e.g., ppt-227130) instead yield 12 bins, with bin 12 actually being a repeat of bin 1 as far as bin min (0 m) and max (5 m) are concerned (but yielding a different 'freq' value).

Please make sure you've pulled the latest from `master`. Better error handling (and an informative error message) was recently added (8cb50c17e2051c41f50acb26c7360f8d741ae8c2) to handle the situation in which the .csv is missing the appropriate header names. The package can't guess what the header names (i.e. bin limits!) should be. Therefore, you'll be asked to manually fix the `-Histos.csv` file and try again.

**Comment by camrinbraun** [comment]
> Yes, we should retain the bins with freq=0 and have the value listed as 0 rather than NA.

You should now be getting the desired (and correct) behavior with 5e31910740b80acdc1361ea67cab2b21d4e79f25

Please test before resolving the issue.

**Comment by marosteg** [comment]
Works!
